services:
  # 前端（Next.js）
  frontend:
    build:
      context: ./leeterview-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NODE_ENV=${NODE_ENV}

  # 後端（.NET Web API）
  backend:
    build:
      context: ./leeterview-backend
      dockerfile: Dockerfile
    ports:
      - "5151:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - NODE_ENV=${NODE_ENV}
    env_file:
      - ./leeterview-backend/.env  # 引用根目錄中的 .env 檔案

