services:
  # 前端（Next.js）
  frontend:
    build:
      context: ./leeterview-frontend
      dockerfile: Dockerfile
    container_name: leeterview-frontend-${COMMIT_HASH}
    env_file:
    - ./leeterview-frontend/.env
    image: leeterview-frontend:${COMMIT_HASH}
    ports:
    - "3000:3000"
    depends_on:
    - backend

  # 後端（.NET Web API）
  backend:
    build:
      context: ./leeterview-backend
      dockerfile: Dockerfile
    container_name: leeterview-backend-${COMMIT_HASH}
    env_file:
    - ./leeterview-backend/.env
    image: leeterview-backend:${COMMIT_HASH}
    ports:
    - 5151:5000


